name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Backend Dependencies
      run: npm ci
      working-directory: ./backend

    - name: Install Frontend Dependencies
      run: npm ci
      working-directory: ./frontend

    - name: Build Backend
      run: npm run build --if-present
      working-directory: ./backend

    - name: Build Frontend
      run: npm run build --if-present
      working-directory: ./frontend

    - name: Set up Environment Variables
      run: |
        touch .env
        echo "${{ secrets.MONGODB_URL }}" > .env
      working-directory: ./backend

    - name: Run Tests for Backend
      run: npm test
      working-directory: ./backend

    - name: Run Tests for Frontend
      run: npm test
      working-directory: ./frontend
